<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\user\Entity\User;
use Drupal\Core\Render\RendererInterface;

/**
 * @file
 * Primary module hooks for KC Personal account module.
 */

/**
 * Implements hook_theme().
 */
function kc_personal_account_theme() {
  return [
    'kc_personal_account_block' => [
      'variables' => [
        'authenticated' => FALSE,
        'username' => '',
        'cart_count' => 0,
      ],
    ],
    'kc_personal_account_cart_button' => [
      'variables' => ['label' => NULL, 'icon_class_name' => NULL, 'attributes' => NULL],
      'template' => 'button--kc-personal-account',
    ],
    'kc_personal_account_modal' => [
      'variables' => [
        'forms' => [],
        'id' => '',
      ],
    ],
    'kc_cart' => [
      'render element' => 'form',
    ],
    'kc_product_cart_link' => [
      'variables' => [
        'attributes' => [],
        'add_to_cart' => [],
        'variations' => [],
        'variation_info' => [],
      ],
    ],
    'kc_add_to_cart' => [
      'variables' => [
        'minus' => [],
        'quantity' => [],
        'plus' => [],
        'attributes' => [],
        'add_to_cart_link' => []
      ],
    ],
    'kc_cart_order_info' => [
      'variables' => [
        'total_price' => '',
        'discount' => 0,
        'total_price_default' => '',
      ],
    ],
    'kc_user_orders' => [
      'variables' => [
        'orders' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function kc_personal_account_preprocess_html(&$variables) {
  if ($variables['user']->isAnonymous()) {
    $form_builder = \Drupal::service('form_builder');
    $login_form =
    $forms['user_login'] = [
      'title' => t('Login'),
      'form' => $form_builder->getForm('Drupal\\user\\Form\\UserLoginForm'),
    ];

    $entity = User::create([]);
    $form_object = \Drupal::entityTypeManager()->getFormObject('user', 'register')->setEntity($entity);

    $forms['user_register'] = [
      'title' => Markup::create(t('Register')),
      'form' => $form_builder->getForm($form_object),
    ];

    $variables['page_bottom']['user_login_modal'] = [
      '#theme' => 'kc_personal_account_modal',
      '#forms' => $forms,
      '#id' => 'kcLoginModal',
    ];
  }
}

/**
 * Implements hook_form_alter().
 */
function kc_personal_account_form_user_register_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_register_form') {
    if (!empty($form['account']['pass'])) {
      $form['account']['pass']['#type'] = 'password';
      $form['account']['pass']['#title'] = t('Password');
    }
  }
}
