<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Markup;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function kc_order_status_theme() {
  return [
    'kc_order_info' => [
      'variables' => [
        'order_entity' => '',
        'state_label' => '',
        'created_date' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_commerce_checkout_pane_form_PANE_ID_alter().
 */
function kc_order_status_commerce_checkout_pane_form_alter(array &$pane_form, FormStateInterface $form_state, array &$complete_form) {
  if (!empty($pane_form['#pane_id'])) {
    $pane_id = $pane_form['#pane_id'];

    $order = $form_state->getFormObject()->getOrder();

    $uid = $order->getCustomerId();
    $current_user = \Drupal::currentUser();

    $entity_manager = \Drupal::entityTypeManager();

    $complete_form['actions']['next']['#attributes'] = [
      'class' => ['rounded-pill'],
    ];

    switch ($pane_id) {
      case 'review':
        if (!$order->get('field_delivery_address')->isEmpty()) {
          $profile = $entity_manager->getStorage('profile')->load($order->field_delivery_address->target_id);
          $view_builder = \Drupal::entityTypeManager()->getViewBuilder('profile');

          $pane_form['selected_address'] = $view_builder->view($profile, 'checkout');
        }

        if (!$order->get('field_shipping_type')->isEmpty()) {
          $pane_form['selected_shipping'] = $order->field_shipping_type->view('full');
          $pane_form['selected_shipping']['#weight'] = -8888;
        }

        break;
      case 'review':
        $complete_form['actions']['next']['#submit'][] = 'kc_order_status_set_order_state_validation';
        break;

      case 'payment_information':
        if (!$order->get('field_shipping_type')->isEmpty()) {
          $shipping_label = $order->field_shipping_type->entity->getName();
          $pane_form['shipping_info'] = [
            '#type' => 'item',
            '#title' => t('Selected shipping method'),
            '#markup' => '<div class="kc-checkout__shipping-info__value">' . $shipping_label . '</div>',
            '#wrapper_attributes' => [
              'class' => ['kc-checkout__shipping-info'],
            ],
          ];
        }

        if ($order->get('field_recipient')->isEmpty()) {
          $storage = $entity_manager->getStorage('profile');

          $result = $storage
            ->getQuery()
            ->accessCheck()
            ->condition('uid', $uid)
            ->condition('type', 'customer')
            ->sort('changed', 'DESC')
            ->execute();

          if (!empty($result)) {
            $id = reset($result);
            $profile = $storage->load($id);

            if (!$profile->get('field_name')->isEmpty()) {
              $pane_form['billing_information']['field_name']['widget'][0]['value']['#default_value'] = $profile->field_name->value;
            }

            if (!$profile->get('field_patronymic')->isEmpty()) {
              $pane_form['billing_information']['field_patronymic']['widget'][0]['value']['#default_value'] = $profile->field_patronymic->value;
            }

            if (!$profile->get('field_surname')->isEmpty()) {
              $pane_form['billing_information']['field_surname']['widget'][0]['value']['#default_value'] = $profile->field_surname->value;
            }

            if (!$profile->get('field_phone')->isEmpty()) {
              $pane_form['billing_information']['field_phone']['widget'][0]['value']['#default_value'] = $profile->field_phone->value;
            }

            if (!$profile->get('field_email')->isEmpty()) {
              $pane_form['billing_information']['field_email']['widget'][0]['value']['#default_value'] = $profile->field_email->value;
            }
            else {
              $pane_form['billing_information']['field_email']['widget'][0]['value']['#default_value'] = $current_user->getEmail();
            }
          }
          else {
            $pane_form['billing_information']['field_email']['widget'][0]['value']['#default_value'] = $current_user->getEmail();
          }
        }

        $pane_form['billing_information']['field_name']['widget'][0]['value']['#title_display'] = 'hidden';
        $pane_form['billing_information']['field_patronymic']['widget'][0]['value']['#title_display'] = 'hidden';
        $pane_form['billing_information']['field_surname']['widget'][0]['value']['#title_display'] = 'hidden';
        $pane_form['billing_information']['field_email']['widget'][0]['value']['#title_display'] = 'hidden';
        $pane_form['billing_information']['field_phone']['widget'][0]['value']['#title_display'] = 'hidden';

        $pane_form['billing_information']['field_name']['#prefix'] = '<div class="row">';
        $pane_form['billing_information']['field_surname']['#suffix'] = '</div>';

        $pane_form['billing_information']['field_name']['#attributes']['class'][] = 'col-md-4';
        $pane_form['billing_information']['field_patronymic']['#attributes']['class'][] = 'col-md-4';
        $pane_form['billing_information']['field_surname']['#attributes']['class'][] = 'col-md-4';

        break;
    }
  }
}

/**
 * If order id draft update order state to "validation".
 */
function kc_order_status_set_order_state_validation(array &$form, FormStateInterface $form_state) {
  $order = $form_state->getFormObject()->getOrder();
  $state_value = $order->getState()->getValue()['value'];

  $cart_provider = \Drupal::service('commerce_cart.cart_provider');
  $cart_provider->finalizeCart($order, 1);
}
