'$schema': 'https://git.drupalcode.org/project/drupal/-/raw/10.1.x/core/modules/sdc/src/metadata.schema.json'
name: Product small inline
status: stable
props:
  type: object
  properties:
    title:
      type: string
      title: Title
      # @todo Add examples here.
      examples: []
    img:
      type: string
      title: Img
      # @todo Add examples here.
      examples: []
    type:
      type: string
      title: Type
      # @todo Add examples here.
      examples: []
    url:
      type: string
      title: Url
      # @todo Add examples here.
      examples: []
    price:
      type: string
      title: Price
      # @todo Add examples here.
      examples: []
