'$schema': 'https://git.drupalcode.org/project/drupal/-/raw/10.1.x/core/modules/sdc/src/metadata.schema.json'
name: product_card_short
status: stable
props:
  type: object
  properties:
    img:
      type: object
      title: Img
      # @todo Add examples here.
      examples: []
    title:
      type: string
      title: Title
      # @todo Add examples here.
      examples: []
    type:
      type: string
      title: Type
      # @todo Add examples here.
      examples: []
    add_to_cart:
      type: object
      title: Add to cart
      # @todo Add examples here.
      examples: []
    url:
      type: string
      title: Product url
      # @todo Add examples here.
      examples: []
    price:
      type: string
      title: Display price
      # @todo Add examples here.
      examples: []
    flag_link:
      type: array
      title: Flag link
